--/lib/core/keyboard/keyboard_codes.lua
-- Contains hexadecimal codes for keyboard input handling.
local keyboard = require("keyboard")


local keyboard_codes = {
    
    -- Function keys
    KEY_F1 = {code = 0x3B, handler = nil},
    KEY_F2 = {code = 0x3C, handler = nil},
    KEY_F3 = {code = 0x3D, handler = nil},
    KEY_F4 = {code = 0x3E, handler = nil},
    KEY_F5 = {code = 0x3F, handler = nil},
    KEY_F6 = {code = 0x40, handler = nil},
    KEY_F7 = {code = 0x41, handler = nil},
    KEY_F8 = {code = 0x42, handler = nil},
    KEY_F9 = {code = 0x43, handler = nil},
    KEY_F10 = {code = 0x44, handler = nil},
    KEY_F11 = {code = 0x57, handler = nil},
    KEY_F12 = {code = 0x58, handler = nil},
    KEY_F13 = {code = 0x64, handler = nil},
    KEY_F14 = {code = 0x65, handler = nil},
    KEY_F15 = {code = 0x66, handler = nil},
    KEY_F16 = {code = 0x67, handler = nil},
    KEY_F17 = {code = 0x68, handler = nil},
    KEY_F18 = {code = 0x69, handler = nil},
    KEY_F19 = {code = 0x71, handler = nil},

    -- Number Keys
    NUM_1 = {code = 0x02, handler = function() return keyboard:typeSymbol("1") end},
    NUM_2 = {code = 0x03, handler = function() return keyboard:typeSymbol("2") end},
    NUM_3 = {code = 0x04, handler = function() return keyboard:typeSymbol("3") end},
    NUM_4 = {code = 0x05, handler = function() return keyboard:typeSymbol("4") end},
    NUM_5 = {code = 0x06, handler = function() return keyboard:typeSymbol("5") end},
    NUM_6 = {code = 0x07, handler = function() return keyboard:typeSymbol("6") end},
    NUM_7 = {code = 0x08, handler = function() return keyboard:typeSymbol("7") end},
    NUM_8 = {code = 0x09, handler = function() return keyboard:typeSymbol("8") end},
    NUM_9 = {code = 0x0A, handler = function() return keyboard:typeSymbol("9") end},
    NUM_0 = {code = 0x0B, handler = function() return keyboard:typeSymbol("0") end},

    -- Operators
    KEY_SUBTRACT = {code = 0x0C, handler = function() return keyboard:typeSymbol("-") end},
    KEY_EQUAL = {code = 0x0D, handler = function() return keyboard:typeSymbol("=") end},
    KEY_BKSPACE = {code = 0x0E, handler = function() return keyboard:backspace() end},
    KEY_TAB = {code = 0x0F, handler = function() return keyboard:typeSymbol("\t") end},
    KEY_CAPSLOCK = {code = 0x3A, handler = function() return keyboard:capsLockToggle() end},
    KEY_LSHIFT = {code = 0x2A, handler = function() return keyboard:shiftToggle() end},
    KEY_RSHIFT = {code = 0x36, handler = function() return keyboard:shiftToggle() end},
    KEY_LCTRL = {code = 0x1D, handler = function() return keyboard:ctrlToggle() end},
    KEY_RCTRL = {code = 0x9D, handler = function() return keyboard:ctrlToggle() end},
    KEY_LALT = {code = 0x38, handler = function() return keyboard:altToggle() end},
    KEY_RALT = {code = 0xB8, handler = function() return keyboard:altToggle() end},
    KEY_SPACE = {code = 0x39, handler = function() return keyboard:typeSymbol(" ") end},
    KEY_ENTER = {code = 0x1C, handler = function() return keyboard:typeSymbol("\n") end},
    KEY_PRT_SCR = {code = 0x00, handler = nil},
    KEY_SCROLL_LOCK = {code = 0x46, handler = nil},
    KEY_PAUSE_BREAK = {code = 0x05, handler = nil},
    KEY_INSERT = {code = 0xD2, handler = nil},
    KEY_HOME = {code = 0xC7, handler = function() return keyboard:home() end},
    KEY_PGUP = {code = 0xC9, handler = function() return keyboard:pageUp() end},
    KEY_DEL = {code = 0xD3, handler = function() return keyboard:delete() end},
    KEY_END = {code = 0xCF, handler = function() return keyboard:endKey() end},
    KEY_PGDN = {code = 0xD1, handler = function() return keyboard:pageDown() end},

    -- Letter Keys
    KEY_A = {code = 0x1E, handler = function() return keyboard:typeLetter("a") end},
    KEY_B = {code = 0x30, handler = function() return keyboard:typeLetter("b") end},
    KEY_C = {code = 0x2E, handler = function() return keyboard:typeLetter("c") end},
    KEY_D = {code = 0x20, handler = function() return keyboard:typeLetter("d") end},
    KEY_E = {code = 0x12, handler = function() return keyboard:typeLetter("e") end},
    KEY_F = {code = 0x21, handler = function() return keyboard:typeLetter("f") end},
    KEY_G = {code = 0x22, handler = function() return keyboard:typeLetter("g") end},
    KEY_H = {code = 0x23, handler = function() return keyboard:typeLetter("h") end},
    KEY_I = {code = 0x17, handler = function() return keyboard:typeLetter("i") end},
    KEY_J = {code = 0x24, handler = function() return keyboard:typeLetter("j") end},
    KEY_K = {code = 0x25, handler = function() return keyboard:typeLetter("k") end},
    KEY_L = {code = 0x26, handler = function() return keyboard:typeLetter("l") end},
    KEY_M = {code = 0x32, handler = function() return keyboard:typeLetter("m") end},
    KEY_N = {code = 0x31, handler = function() return keyboard:typeLetter("n") end},
    KEY_O = {code = 0x18, handler = function() return keyboard:typeLetter("o") end},
    KEY_P = {code = 0x19, handler = function() return keyboard:typeLetter("p") end},
    KEY_Q = {code = 0x10, handler = function() return keyboard:typeLetter("q") end},
    KEY_R = {code = 0x13, handler = function() return keyboard:typeLetter("r") end},
    KEY_S = {code = 0x1F, handler = function() return keyboard:typeLetter("s") end},
    KEY_T = {code = 0x14, handler = function() return keyboard:typeLetter("t") end},
    KEY_U = {code = 0x16, handler = function() return keyboard:typeLetter("u") end},
    KEY_V = {code = 0x2F, handler = function() return keyboard:typeLetter("v") end},
    KEY_W = {code = 0x11, handler = function() return keyboard:typeLetter("w") end},
    KEY_X = {code = 0x2D, handler = function() return keyboard:typeLetter("x") end},
    KEY_Y = {code = 0x15, handler = function() return keyboard:typeLetter("y") end},
    KEY_Z = {code = 0x2C, handler = function() return keyboard:typeLetter("z") end},

    -- Special Characters
    KEY_GRAVE_ACCENT = {code = 0x29, handler = function() return keyboard:typeSymbol("`") end},
    KEY_SEMICOLON = {code = 0x27, handler = function() return keyboard:typeSymbol(";") end},
    KEY_COMMA = {code = 0x33, handler = function() return keyboard:typeSymbol(",") end},
    KEY_PERIOD = {code = 0x34, handler = function() return keyboard:typeSymbol(".") end},
    KEY_SLASH = {code = 0x35, handler = function() return keyboard:typeSymbol("/") end},
    KEY_BACKSLASH = {code = 0x2B, handler = function() return keyboard:typeSymbol("\\") end},
    KEY_LEFT_BRACKET = {code = 0x1A, handler = function() return keyboard:typeSymbol("[") end},
    KEY_RIGHT_BRACKET = {code = 0x1B, handler = function() return keyboard:typeSymbol("]") end},
    KEY_APOSTROPHE = {code = 0x28, handler = function() return keyboard:typeSymbol("'") end},

    -- Navigation Keys
    KEY_LEFT_ARROW = {code = 0xCB, handler = function() return keyboard:leftArrow() end},
    KEY_RIGHT_ARROW = {code = 0xCD, handler = function() return keyboard:rightArrow() end},
    KEY_UP_ARROW = {code = 0xC8, handler = function() return keyboard:upArrow() end},
    KEY_DOWN_ARROW = {code = 0xD0, handler = function() return keyboard:downArrow() end},

    -- Numpad Keys
    NUMPAD_0 = {code = 0x52, handler = function() return keyboard:typeSymbol("0") end},
    NUMPAD_1 = {code = 0x4F, handler = function() return keyboard:typeSymbol("1") end},
    NUMPAD_2 = {code = 0x50, handler = function() return keyboard:typeSymbol("2") end},
    NUMPAD_3 = {code = 0x51, handler = function() return keyboard:typeSymbol("3") end},
    NUMPAD_4 = {code = 0x4B, handler = function() return keyboard:typeSymbol("4") end},
    NUMPAD_5 = {code = 0x4C, handler = function() return keyboard:typeSymbol("5") end},
    NUMPAD_6 = {code = 0x4D, handler = function() return keyboard:typeSymbol("6") end},
    NUMPAD_7 = {code = 0x47, handler = function() return keyboard:typeSymbol("7") end},
    NUMPAD_8 = {code = 0x48, handler = function() return keyboard:typeSymbol("8") end},
    NUMPAD_9 = {code = 0x49, handler = function() return keyboard:typeSymbol("9") end},
    NUMPAD_SLASH = {code = 0xB5, handler = function() return keyboard:typeSymbol("/") end},
    NUMPAD_ASTERISK = {code = 0x37, handler = function() return keyboard:typeSymbol("*") end},
    NUMPAD_SUBTRACT = {code = 0x4A, handler = function() return keyboard:typeSymbol("-") end},
    NUMPAD_ADD = {code = 0x4E, handler = function() return keyboard:typeSymbol("+") end},
    NUMPAD_ENTER = {code = 0x9C, handler = function() return keyboard:typeSymbol("\n") end},
    NUMPAD_LOCK = {code = 0x45, handler = nil},
    NUMPAD_PERIOD = {code = 0x53, handler = function() return keyboard:typeSymbol(".") end},

    -- Japanese Keys
    -- Note these were carried over from OpenOS, I don't own any japanese keys. Do with them as you like.
    KEY_KANA = {code = 0x70, handler = nil},
    KEY_KANJI = {code = 0x94, handler = nil},
    KEY_CONVERT = {code = 0x79, handler = nil},
    KEY_NOCONVERT = {code = 0x7B, handler = nil},
    KEY_YEN = {code = 0x7D, handler = nil},
    KEY_CIRCUMFLEX = {code = 0x90, handler = nil},
    KEY_AX = {code = 0x96, handler = nil}
}
return keyboard_codes